spring:
  application:
    name: wardrobe-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: false

  # R2DBC configuration
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wardrobe_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
